;this file for FamiTone2 library generated by text2data tool

desprolijo_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env2,.env0,.env4
	.db $00
	.db $30 ;instrument $02
	.dw .env3,.env0,.env0
	.db $00
	.db $b0 ;instrument $03
	.dw .env2,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $c8,$c7,$c6,$c6,$c5,$03,$c4,$03,$c3,$02,$c2,$03,$c1,$c1,$c0,$00
	.db $0e
.env2:
	.db $c8,$c5,$c4,$c1,$c0,$00,$04
.env3:
	.db $cc,$c7,$c4,$c3,$c2,$c0,$00,$05
.env4:
	.db $ff,$00,$00


.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $80,$44,$83,$44,$85,$3c,$3c,$3c,$44,$83,$44,$89,$44,$83,$44,$85
	.db $3c,$3c,$3c,$44,$83,$44,$89,$44,$83,$44,$85,$3c,$3c,$3c
.ref1:
	.db $44,$83,$44,$89,$44,$83,$44,$85,$3c,$3c,$3c,$44,$83,$44,$91,$44
	.db $85,$40,$85,$3c,$85,$40,$85
.ref2:
	.db $df
.ref3:
	.db $df
.ref4:
	.db $44,$83,$44,$83,$4a,$83,$4e,$83,$52,$83,$4e,$83,$4a,$83,$4e,$83
	.db $4e,$83,$4a,$a7
	.db $ff,$14
	.dw .ref4
	.db $ff,$14
	.dw .ref4
	.db $ff,$14
	.dw .ref4
.ref8:
	.db $8f,$44,$4a,$44,$4a,$83,$44,$4f,$4e,$83,$4a,$4e,$4a,$4e,$83,$4a
	.db $53,$52,$a3
.ref9:
	.db $4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e
	.db $4a,$4e,$44,$ad,$44,$83,$44,$83
.ref10:
	.db $4a,$83,$4e,$83,$52,$83,$4e,$83,$4a,$83,$4e,$83,$4e,$83,$4a,$a7
	.db $44,$83,$44,$83
	.db $ff,$14
	.dw .ref10
	.db $ff,$14
	.dw .ref10
.ref13:
	.db $4a,$83,$4e,$83,$52,$83,$4e,$83,$4a,$83,$4e,$83,$4e,$83,$4a,$b3
.ref14:
	.db $83,$44,$4a,$44,$4a,$83,$44,$4f,$4e,$83,$4a,$4e,$4a,$4e,$83,$4a
	.db $53,$52,$a3,$4a,$4e,$4a,$4e,$4a,$4e
.ref15:
	.db $4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$44,$b1,$44,$4a
	.db $44,$4a,$83,$44,$4f,$4e
.ref16:
	.db $83,$4a,$4e,$4a,$4e,$83,$4a,$53,$4c,$a3,$4a,$4e,$4a,$4e,$4a,$4e
	.db $4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e
.ref17:
	.db $44,$dd
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref18:
	.db $df
.ref19:
	.db $df
.ref20:
	.db $86,$44,$44,$44,$4a,$4e,$4a,$44,$44,$44,$4a,$44,$4a,$44,$44,$44
	.db $4a,$4e,$4a,$44,$44,$44,$4a,$44,$4a,$44,$44,$44,$4a,$4e,$4a,$44
	.db $44,$44,$4a,$44,$4a,$44,$44,$44,$4a,$4e,$4a,$44,$44,$44,$4a,$44
	.db $4a
.ref21:
	.db $44,$44,$44,$4a,$4e,$4a,$44,$44,$44,$4a,$44,$4a,$44,$44,$44,$4a
	.db $4e,$4a,$44,$44,$44,$4a,$44,$4a,$44,$44,$44,$4a,$4e,$4a,$44,$44
	.db $44,$4a,$44,$4a,$44,$44,$44,$4a,$4e,$4a,$44,$44,$44,$4a,$44,$4a
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $ff,$30
	.dw .ref21
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref36:
	.db $df
.ref37:
	.db $df
.ref38:
	.db $df
.ref39:
	.db $82,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85
	.db $33,$32,$85,$33,$32,$85,$33,$32,$85
.ref40:
	.db $33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33
	.db $32,$85,$33,$32,$85,$33,$32,$85
	.db $ff,$18
	.dw .ref40
	.db $ff,$18
	.dw .ref40
	.db $ff,$18
	.dw .ref40
.ref44:
	.db $33,$33,$33,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33
	.db $32,$85,$33,$32,$85,$33,$32,$85
	.db $ff,$18
	.dw .ref40
	.db $ff,$18
	.dw .ref40
	.db $ff,$18
	.dw .ref40
	.db $ff,$18
	.dw .ref40
.ref49:
	.db $33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33
	.db $32,$85,$33,$32,$85,$33,$33,$32,$81
	.db $ff,$18
	.dw .ref40
	.db $ff,$18
	.dw .ref40
	.db $ff,$18
	.dw .ref40
.ref53:
	.db $33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$b5
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref54:
	.db $df
.ref55:
	.db $df
.ref56:
	.db $df
.ref57:
	.db $85,$84,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89
	.db $08,$83
.ref58:
	.db $85,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08
	.db $83
	.db $ff,$11
	.dw .ref58
	.db $ff,$11
	.dw .ref58
	.db $ff,$11
	.dw .ref58
.ref62:
	.db $91,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$83
	.db $ff,$11
	.dw .ref58
	.db $ff,$11
	.dw .ref58
	.db $ff,$11
	.dw .ref58
	.db $ff,$11
	.dw .ref58
.ref67:
	.db $85,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$8f
	.db $ff,$11
	.dw .ref58
	.db $ff,$11
	.dw .ref58
	.db $ff,$11
	.dw .ref58
.ref71:
	.db $85,$08,$89,$08,$89,$08,$89,$08,$b3
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref72:
	.db $df
.ref73:
	.db $df
.ref74:
	.db $df
.ref75:
	.db $df
.ref76:
	.db $df
.ref77:
	.db $df
.ref78:
	.db $df
.ref79:
	.db $df
.ref80:
	.db $df
.ref81:
	.db $df
.ref82:
	.db $df
.ref83:
	.db $df
.ref84:
	.db $df
.ref85:
	.db $df
.ref86:
	.db $df
.ref87:
	.db $df
.ref88:
	.db $df
.ref89:
	.db $df
	.db $fd
	.dw .song0ch4loop
