;this file for FamiTone2 library generated by text2data tool

desprolijo_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env2,.env0,.env4
	.db $00
	.db $30 ;instrument $02
	.dw .env3,.env0,.env0
	.db $00
	.db $30 ;instrument $03
	.dw .env2,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $c8,$c7,$c6,$c6,$c5,$03,$c4,$03,$c3,$02,$c2,$03,$c1,$c1,$c0,$00
	.db $0e
.env2:
	.db $c8,$c5,$c4,$c1,$c0,$00,$04
.env3:
	.db $cc,$c7,$c4,$c3,$c2,$c0,$00,$05
.env4:
	.db $ff,$00,$00


.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $80,$44,$83,$44,$85,$3c,$3c,$3c,$44,$83,$44,$89,$44,$83,$44,$85
	.db $3c,$3c,$3c,$44,$83,$44,$89,$44,$83,$44,$85,$3c,$3c,$3c
.ref1:
	.db $44,$83,$44,$89,$44,$83,$44,$85,$3c,$3c,$3c,$44,$83,$44,$91,$44
	.db $85,$40,$85,$3c,$85,$40,$85
.ref2:
	.db $df
.ref3:
	.db $df
.ref4:
	.db $44,$83,$44,$83,$4a,$83,$4e,$83,$52,$83,$4e,$83,$4a,$83,$4e,$83
	.db $4e,$83,$4a,$a7
	.db $ff,$14
	.dw .ref4
	.db $ff,$14
	.dw .ref4
	.db $ff,$14
	.dw .ref4
.ref8:
	.db $8f,$44,$4a,$44,$4a,$83,$44,$4f,$4e,$83,$4a,$4e,$4a,$4e,$83,$4a
	.db $53,$52,$a3
.ref9:
	.db $4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e
	.db $4a,$4e,$4a,$4e,$4a,$4e,$4a,$4e,$44,$ad
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref10:
	.db $df
.ref11:
	.db $df
.ref12:
	.db $86,$44,$44,$44,$4a,$4e,$4a,$44,$44,$44,$4a,$44,$4a,$44,$44,$44
	.db $4a,$4e,$4a,$44,$44,$44,$4a,$44,$4a,$44,$44,$44,$4a,$4e,$4a,$44
	.db $44,$44,$4a,$44,$4a,$44,$44,$44,$4a,$4e,$4a,$44,$44,$44,$4a,$44
	.db $4a
.ref13:
	.db $44,$44,$44,$4a,$4e,$4a,$44,$44,$44,$4a,$44,$4a,$44,$44,$44,$4a
	.db $4e,$4a,$44,$44,$44,$4a,$44,$4a,$44,$44,$44,$4a,$4e,$4a,$44,$44
	.db $44,$4a,$44,$4a,$44,$44,$44,$4a,$4e,$4a,$44,$44,$44,$4a,$44,$4a
	.db $ff,$30
	.dw .ref13
	.db $ff,$30
	.dw .ref13
	.db $ff,$30
	.dw .ref13
	.db $ff,$30
	.dw .ref13
	.db $ff,$30
	.dw .ref13
	.db $ff,$30
	.dw .ref13
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref20:
	.db $df
.ref21:
	.db $df
.ref22:
	.db $df
.ref23:
	.db $82,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85
	.db $33,$32,$85,$33,$32,$85,$33,$32,$85
.ref24:
	.db $33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33
	.db $32,$85,$33,$32,$85,$33,$32,$85
	.db $ff,$18
	.dw .ref24
	.db $ff,$18
	.dw .ref24
	.db $ff,$18
	.dw .ref24
.ref28:
	.db $33,$33,$33,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33,$32,$85,$33
	.db $32,$85,$33,$32,$85,$33,$32,$85
	.db $ff,$18
	.dw .ref24
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref30:
	.db $df
.ref31:
	.db $df
.ref32:
	.db $df
.ref33:
	.db $85,$84,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89
	.db $08,$83
.ref34:
	.db $85,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08
	.db $83
	.db $ff,$11
	.dw .ref34
	.db $ff,$11
	.dw .ref34
	.db $ff,$11
	.dw .ref34
.ref38:
	.db $91,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$89,$08,$83
	.db $ff,$11
	.dw .ref34
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref40:
	.db $df
.ref41:
	.db $df
.ref42:
	.db $df
.ref43:
	.db $df
.ref44:
	.db $df
.ref45:
	.db $df
.ref46:
	.db $df
.ref47:
	.db $df
.ref48:
	.db $df
.ref49:
	.db $df
	.db $fd
	.dw .song0ch4loop
